/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InnerComponent {
        "foo": boolean;
    }
    interface TestComponent {
        "foo": boolean;
    }
}
declare global {
    interface HTMLInnerComponentElement extends Components.InnerComponent, HTMLStencilElement {
    }
    var HTMLInnerComponentElement: {
        prototype: HTMLInnerComponentElement;
        new (): HTMLInnerComponentElement;
    };
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "inner-component": HTMLInnerComponentElement;
        "test-component": HTMLTestComponentElement;
    }
}
declare namespace LocalJSX {
    interface InnerComponent {
        "foo"?: boolean;
    }
    interface TestComponent {
        "foo"?: boolean;
    }
    interface IntrinsicElements {
        "inner-component": InnerComponent;
        "test-component": TestComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "inner-component": LocalJSX.InnerComponent & JSXBase.HTMLAttributes<HTMLInnerComponentElement>;
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
        }
    }
}
